### ISSUE TITLE
License

### ISSUE THREAD

**Issue by arybczak** [haskellari/tree-diff#63]
Hey,

Any particular reason why this package used to be BSD licensed, but was changed to GPL?

**Comment by phadej** [comment]
Because i feel that GPL is a way to force proprietary users to give back.

There was a company which made a change to `tree-diff` because it lacked a feature, but didn't contribute it back. When I learned about it, I implemented that feature and changed the license to GPL.

Since around then, I default my free time projects to GPL.

**Comment by arybczak** [comment]
Fair enough :+1:
